### PR TITLE
Added new Guide re embeddings

### PR DESCRIPTION
**Pull request by Dan-Cleary**
Added new Guide re embeddings

### CODE REVIEW

**Comment by snwfdhmp** [comment]
Great resource, thanks !

**Comment by snwfdhmp** [comment]
@Dan-Cleary may i have access to https://www.prompthub.us/ ?

**Comment by Dan-Cleary** [comment]
Yeah no problem, what's your email address?

**Comment by snwfdhmp** [comment]
@Dan-Cleary Thanks ! My email address is snwfdhmp@gmail.com

**Pull request merged**
